### ISSUE TITLE
[REFACTOR] 라우터/페이지별 API 에러 핸들링을 구현합니다

### ISSUE THREAD

**Issue by HyoKyoungLee** [Team-4yclingHomerun/4yclinghomerun-client#73]
## 📄 Describe

- 라우터/페이지별 API 에러 핸들링을 구현합니다

## ☑️ Tasks

- [x] Router 에러
  - 페이지를 진입할 때 지정되지 않은 경로로 들어가면 NotFoundPage를 보여줍니다
  - NotFoundPage에는 "이전 페이지로 돌아가기"와 "홈 화면으로 가기" 버튼을 구현합니다
- [x] 페이지별 API 에러
  - 페이지별 API에서 발생하는 에러를 핸들링합니다
  - 기존에 활용하지 않았던 axios의 intercepter에서 에러를 핸들링합니다
  - 공통 에러 컴포넌트를 퍼블리싱하여 최대한 많은 페이지에서 활용할 수 있도록 합니다

### Router 에러
- 기존 KT Wiz 홈페이지 : Router 에러 처리 없음
![image](https://github.com/user-attachments/assets/e526c9d5-315a-44f1-9566-3296385fa620)

- 레퍼런스
![image](https://github.com/user-attachments/assets/9f356af9-575e-49d8-9e7b-0ae262226cc1)
![image](https://github.com/user-attachments/assets/2f404153-027b-4b37-992b-b249de56856f)

### 페이지별 API 에러
![image](https://github.com/user-attachments/assets/5e273272-65bd-43fa-a36c-ce0c6a42bcc6)
![image](https://github.com/user-attachments/assets/5b618d26-c0c7-4cfc-96af-2c8225e992e8)

**Comment by bbjbc** [comment]
404 레퍼런스 2번째 사진 깔끔하고 보기 좋네요!

**Comment by jungkyuYang** [comment]
추가 기능 구현도 고민하셨군요 좋은 이슈 같습니다 👍
